require_relative '../library/person'
require_relative '../library/book'
require_relative '../library/student'
require_relative '../library/teacher'
require_relative '../library/rental'
require_relative '../library/classroom'
require_relative '../library/corrector'
